version: '3.8'

name: "neo-bank-core"

services:
  # 1. Database (PostgreSQL)
  postgres:
    image: postgres:16-alpine
    container_name: bank-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    # We map port 5432 to host so you can check DB via DBeaver/pgAdmin
    ports:
      - "5432:5432"
    # Create multiple databases on startup
    volumes:
      - ./init-sql:/docker-entrypoint-initdb.d
    networks:
      - bank-network

  # 2. Distributed Tracing (Zipkin) - Vital for microservices
  zipkin:
    image: openzipkin/zipkin
    container_name: bank-zipkin
    ports:
      - "9411:9411"
    networks:
      - bank-network

  # 3. Message Broker (Kafka + Zookeeper)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: bank-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - bank-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: bank-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - bank-network

  # --- MICROSERVICES ---
  account-service:
    build: ./account-service
    container_name: bank-account-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/account_db
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    depends_on:
      - postgres
      - kafka
      - zipkin
    networks:
      - bank-network

  transaction-service:
    build: ./transaction-service
    container_name: bank-transaction-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/transaction_db
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
      # Point to the container name of account-service, not localhost!
      ACCOUNT_SERVICE_URL: http://account-service:8081
    depends_on:
      - postgres
      - kafka
      - zipkin
      - account-service
    networks:
      - bank-network
networks:
  bank-network:
    driver: bridge