server:
  port: 8081 # Account Service runs on 8081

spring:
  application:
    name: account-service
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/account_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Automatically creates tables (Good for dev, bad for prod)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    template:
      observation-enabled: true  # <--- ADD THIS (Enable Tracing for Producer)
    listener:
      observation-enabled: true  # <--- ADD THIS (Enable Tracing for Consumer)
    consumer:
      group-id: account-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  tracing:
    sampling:
      probability: 1.0 # Log 100% of requests (Don't do this in Prod!)
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/